require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IntendedTripsController do

  # This should return the minimal set of attributes required to create a valid
  # IntendedTrip. As you add validations to IntendedTrip, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IntendedTripsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all intended_trips as @intended_trips" do
      intended_trip = IntendedTrip.create! valid_attributes
      get :index, {}, valid_session
      assigns(:intended_trips).should eq([intended_trip])
    end
  end

  describe "GET show" do
    it "assigns the requested intended_trip as @intended_trip" do
      intended_trip = IntendedTrip.create! valid_attributes
      get :show, {:id => intended_trip.to_param}, valid_session
      assigns(:intended_trip).should eq(intended_trip)
    end
  end

  describe "GET new" do
    it "assigns a new intended_trip as @intended_trip" do
      get :new, {}, valid_session
      assigns(:intended_trip).should be_a_new(IntendedTrip)
    end
  end

  describe "GET edit" do
    it "assigns the requested intended_trip as @intended_trip" do
      intended_trip = IntendedTrip.create! valid_attributes
      get :edit, {:id => intended_trip.to_param}, valid_session
      assigns(:intended_trip).should eq(intended_trip)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IntendedTrip" do
        expect {
          post :create, {:intended_trip => valid_attributes}, valid_session
        }.to change(IntendedTrip, :count).by(1)
      end

      it "assigns a newly created intended_trip as @intended_trip" do
        post :create, {:intended_trip => valid_attributes}, valid_session
        assigns(:intended_trip).should be_a(IntendedTrip)
        assigns(:intended_trip).should be_persisted
      end

      it "redirects to the created intended_trip" do
        post :create, {:intended_trip => valid_attributes}, valid_session
        response.should redirect_to(IntendedTrip.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved intended_trip as @intended_trip" do
        # Trigger the behavior that occurs when invalid params are submitted
        IntendedTrip.any_instance.stub(:save).and_return(false)
        post :create, {:intended_trip => {}}, valid_session
        assigns(:intended_trip).should be_a_new(IntendedTrip)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IntendedTrip.any_instance.stub(:save).and_return(false)
        post :create, {:intended_trip => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested intended_trip" do
        intended_trip = IntendedTrip.create! valid_attributes
        # Assuming there are no other intended_trips in the database, this
        # specifies that the IntendedTrip created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IntendedTrip.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => intended_trip.to_param, :intended_trip => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested intended_trip as @intended_trip" do
        intended_trip = IntendedTrip.create! valid_attributes
        put :update, {:id => intended_trip.to_param, :intended_trip => valid_attributes}, valid_session
        assigns(:intended_trip).should eq(intended_trip)
      end

      it "redirects to the intended_trip" do
        intended_trip = IntendedTrip.create! valid_attributes
        put :update, {:id => intended_trip.to_param, :intended_trip => valid_attributes}, valid_session
        response.should redirect_to(intended_trip)
      end
    end

    describe "with invalid params" do
      it "assigns the intended_trip as @intended_trip" do
        intended_trip = IntendedTrip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IntendedTrip.any_instance.stub(:save).and_return(false)
        put :update, {:id => intended_trip.to_param, :intended_trip => {}}, valid_session
        assigns(:intended_trip).should eq(intended_trip)
      end

      it "re-renders the 'edit' template" do
        intended_trip = IntendedTrip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IntendedTrip.any_instance.stub(:save).and_return(false)
        put :update, {:id => intended_trip.to_param, :intended_trip => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested intended_trip" do
      intended_trip = IntendedTrip.create! valid_attributes
      expect {
        delete :destroy, {:id => intended_trip.to_param}, valid_session
      }.to change(IntendedTrip, :count).by(-1)
    end

    it "redirects to the intended_trips list" do
      intended_trip = IntendedTrip.create! valid_attributes
      delete :destroy, {:id => intended_trip.to_param}, valid_session
      response.should redirect_to(intended_trips_url)
    end
  end

end
